repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    - id: markdownlint
-   repo: local
    hooks:
    - id: cargo-audit
      name: cargo-audit
      entry: cargo audit
      pass_filenames: false
      always_run: true
      language: rust
-   repo: local
    hooks:
    - id: cargo-fmt
      name: cargo-fmt
      entry: cargo fmt -- --check
      pass_filenames: false
      always_run: true
      language: rust
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.2.1
  hooks:
  - id: shellcheck
    files: bin/commit
